name: CI/CD Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Installer PHP et Composer
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12' # Adapter la version de PHP si nécessaire
          extensions: mbstring, pdo, curl
          tools: composer

      - name: Install Composer Dependencies
        run: composer update

      # Étape 3 : Installer Node.js et les dépendances npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0' # Adapter la version de Node.js si nécessaire

      - name: Install NPM Dependencies
        run: npm install

      # Étape 4 : Build Tailwind CSS
      - name: Build Tailwind CSS
        run: npm install -g tailwindcss

      # Étape 5 : Lancer les tests PHPUnit
      - name: Run PHPUnit Tests
        run: ./vendor/bin/phpunit tests

  merge_branch:
    name: Merge Branches
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Merge Branches
        run: |
          git config --global user.name "Abde-Ait-bella"
          git config --global user.email "abdessamadaitbella1998@gmail.com"
          git switch main
          git merge --no-ff develop 
          git push origin main

  # deploy:
  #   name: Deploy via FTP
  #   runs-on: ubuntu-latest
  #   needs: merge_branch

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Deploy via FTP
  #       uses: SamKirkland/FTP-Deploy-Action@4.3.0
  #       with:
  #         server: ${{ secrets.FTP_SERVER }}
  #         username: ${{ secrets.FTP_USERNAME }}
  #         password: ${{ secrets.FTP_PASSWORD }}
  #         local-dir: ./ # Remplacez par le chemin du projet si nécessaire
